### ISSUE TITLE
Does setting async to false ensure the scripts load in order?

### ISSUE THREAD

**Issue by kotAPI** [MiguelCastillo/load-js#24]
Hi Miguel. I need to load scripts in order,... second script depends on the first.. if I set it to false, can I be sure one loads after another?

EDIT: Also, is there a catch or error method I can use to catch script load failures?

**Comment by MiguelCastillo** [comment]
Sorry I didnt notice this issue here.  Yeah scripts should load in order unless you set them to async.  Let me know if this is not happening.
