### ISSUE TITLE
Updating release version

### ISSUE THREAD

**Issue by angiedemarc** [MiguelCastillo/load-js#30]
Hello,
I noticed that the code in this repo is more recent than the latest release, which hasn't been updated since 2018 (https://github.com/MiguelCastillo/load-js/releases). There are two commits that occurred after version 3.0.3 (https://github.com/MiguelCastillo/load-js/pulls?q=is%3Apr+is%3Aclosed). Is it possible to update the npm package to include these changes? Thanks!

**Comment by MiguelCastillo** [comment]
published 3.1.0 https://github.com/MiguelCastillo/load-js/releases/tag/v3.1.0.  I have not looked in this repo in so long!
