### ISSUE TITLE
Broken release of 3.1.0

### ISSUE THREAD

**Issue by isemanjski** [MiguelCastillo/load-js#31]
Hi, seems that `index.js` and `index.js.map` are missing from the latest release (**v3.1.0**) which causes builds to fail.

You can use NPM code explorer to see the contents of the published package. [Here](https://www.npmjs.com/package/load-js/v/3.1.0?activeTab=explore) you can see the contents of v3.1.0, and [here](https://www.npmjs.com/package/load-js/v/3.0.3?activeTab=explore) of v3.0.3.

When I clone the repository and run `npm run build` I can see both files being generated, and when I run `npm pack` I see that both files are being added to the npm package.

**Comment by MiguelCastillo** [comment]
thanks for logging this! i will redeploy a patch shortly. im sorry for the inconvenience.

**Comment by MiguelCastillo** [comment]
just deployed a patch https://www.npmjs.com/package/load-js/v/3.1.1?activeTab=explore.  Thanks again!

**Comment by isemanjski** [comment]
Thank you for your swift response, I can confirm it is working now
