### ISSUE TITLE
Should not write multiple scripts with same ID

### ISSUE THREAD

**Issue by allpro** [MiguelCastillo/load-js#8]
The main purpose of tagging a script with an ID is so it's easy to check if it's already loaded. However this library doesn't check this, forcing users to add a wrapper to do this simple test. **This should be built-in, as shown below.** 
 
```javascript
if ( options.hasOwnProperty("id") ) {
    var existingScript = document.getElementById( options.id );
    if ( existingScript ) {
        // script already loaded; ABORT and return a resolved promise
        return Promise.resolve( existingScript );
    }
 
    // set the ID and continue loading
    script.id = options.id;
}
```
 
There _could_ be an option to disable this automation, but if the user doesn't care about writing the same script multiple times, they can simply _not_ pass an id!
 
Sorry; I don't have time to fork and create a pull request, but the snippet above has everything you need.

**Comment by MiguelCastillo** [comment]
The main purpose for the ID is to be able to reference the node later, not to be used for caching by load-js.  Although you do raise a good point, which is that we shouldn't load something if we have already loaded it.

I have thought about adding caching before, which is basically what we are talking about here. But caching should be based on URL; using the ID puts a restriction that seems unnecessary.  Or are you thinking that *only* supporting ID has specific benefits over caching by URL?

**Comment by MiguelCastillo** [comment]
there is the PR for caching. I am happy to leave this issue open and accept PRs to address issues not addressed in the caching PR.

**Comment by allpro** [comment]
I agree that existence tests _should_, by default, check by src to catches scripts not loaded by this utility, eg:
```javascript
head.querySelector(`script[src="${script.url}"]')
```

There is more than one URL that might load the same library, like singularly or in a combined package. I guess this is a use-case for searching by ID _outside_ this helper. (Only one I can think of.)

However, by definition an ID should be unique. So if adding an element with an ID, it imposes a duty to avoid duplicates. At a minimum a warning should be logged because this indicates some type of coding error, which may escape detection otherwise

**Comment by MiguelCastillo** [comment]
ok - i think i understand the issue you are trying to solve by querying the DOM. You are concerned that the element with the a particular ID/URL might already exist that was *not* loaded by `load-js`?

Is that currently an issue you are running into or is this more of an academic exercise?

Logging a warning { if the the item is not cached and it already exists in the DOM } seems like a fair request. I would happily take a PR. :)

**Comment by MiguelCastillo** [comment]
@allpro i have added logic to handle situations when scripts already exists in the DOM with a given ID or URL.  Do mind taking a look?

https://github.com/MiguelCastillo/load-js/pull/16

**Comment by MiguelCastillo** [comment]
changes merged in https://github.com/MiguelCastillo/load-js/pull/16
